name: Build the LaTeX documents
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk
      - name: Clean the build directory
        run: find build ! -name '*.pdf' -type f -exec sudo rm -f {} +
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: rirekisho-${{ steps.slug.outputs.sha7 }}
          path: build
